### ISSUE TITLE
Extracting Poses From RTABMAP

### ISSUE THREAD

**Issue by lakshmikanth-nageswar** [introlab/rtabmap_ros#1169]
Is it possible to extract all the poses against every input RGBD frame to RTABMAP? I've tried all the options in File->Export Poses but none of them match the input frames of RGBD.

Your help would be greatly appreciated !

**Comment by matlabbe** [comment]
It is because rtabmap would run at a slower rate than camera frame rate/ odometry rate. To record poses at least at odometry rate without causing significant more computation burden for rtabmap is to enable `Rtabmap/CreateIntermediateNodes`. With `rtabmap-databaseViewer`, you should be then able to export all poses.
