### ISSUE TITLE
Rtabmap fatal error UException.

### ISSUE THREAD

**Issue by brayanpa** [introlab/rtabmap_ros#1187]
Hello,

I'm experiencing an intermittent bug with rtabmap on ROS Humble. Rtabmap occasionally crashes without a consistent pattern. Sometimes it runs for several hours without issue, while other times it crashes shortly after launch.

I have not been able to identify specific steps to reliably reproduce the problem.

Any help or suggestions would be greatly appreciated.

Thank you!

Here are the commits I am currently using:

```
rtabmap commit e619c577595ad221890d550ea3dbe6cbdebe9502
rtabmap_ros commit 2f365ab7e10025c4d13b7855dfb4b7c8bb01f2d3
```

Additionally, here are some logs from the crashes:

[errorRtabmap.txt](https://github.com/user-attachments/files/16340126/errorRtabmap.txt)

[RtabmapUEXerrror.txt](https://github.com/user-attachments/files/16340135/RtabmapUEXerrror.txt)

**Comment by matlabbe** [comment]
Hi, 

Thank you for the logs, they were helpful to find the bug. I see two scenarios that this error could happen (that are now fixed in the commit above):
1. With `Rtabmap/CreateIntermediateNodes=true` and providing external landmarks (e.g., from apriltag ros node)
2. Providing external landmarks (e.g., from apriltag ros node), with `subscribe_depth` and `subscribe_rgb` set to false (no images subscribed) and only subscribing to a laser scan/point cloud (`subscribe_scan` or `subscribe_scan_cloud` are true), and **then at some point the scans received are empty** while some landmarks in the map are still detected. I think this is what happens in your case.

Upgrade/reinstall [rtabmap](https://github.com/introlab/rtabmap) to latest version to resolve this issue, or let me know if it happens again.

cheers,
Mathieu
