### ISSUE TITLE
rtabmap_ros/RGBDImage.h: No such file or directory

### ISSUE THREAD

**Issue by willdzeng** [introlab/rtabmap_ros#126]
Hey Mathiue,

In file included from /home/tr/test/src/rtabmap_ros/include/rtabmap_ros/CoreWrapper.h:53:0,
                 from /home/tr/test/src/rtabmap_ros/src/CoreNode.cpp:28:
/home/tr/test/src/rtabmap_ros/include/rtabmap_ros/CommonDataSubscriber.h:48:35: fatal error: rtabmap_ros/RGBDImage.h: No such file or directory
 #include <rtabmap_ros/RGBDImage.h>

I try to build the recent commits, it gives me this error when I first do catkin_make.
But it disappeared when I do the catkin_make second time.

Where is this RGBDImage.h file? I couldn't find it. Is it generated automatically or something?

**Comment by matlabbe** [comment]
The commit above should fix the problem. RGBDImage.h is generated when rtabmap's ROS messages are generated. CoreNode.cpp was built in parallel to ros messages and depended on CoreWrapper.h (which depended on RGBDImage.h), so it the error happened only if the ROS messages were not yet generated. The second time it worked because the message header was already generated. I removed the dependency to CoreWrapper.h so CoreNode.cpp can be correctly built in parallel to messages.

thx for reporting!
