### ISSUE TITLE
What does move_base do when building a map?

### ISSUE THREAD

**Issue by willzoe** [introlab/rtabmap_ros#380]
When I read the launch file in the tutorial [Stereo Outdoor Mapping](http://wiki.ros.org/rtabmap_ros/Tutorials/StereoOutdoorMapping), I found that `move_base` was not used; however, when I read the launch file in the tutorial [Mapping and Navigation with Turtlebot](http://wiki.ros.org/rtabmap_ros/Tutorials/MappingAndNavigationOnTurtlebot), I found that `move_base` was used. It seems that in these two tutorials, the keyboard is used to control the robot movement to build the map.
Therefore, I would like to know how the use of `move_base` affects the results of the mapping, and what role does `move_base` play in the mapping process?

**Comment by matlabbe** [comment]
For stereo outdoor mapping, a gamepad was used to operate the robot. For the Mapping and Navigation with Turtlebot example, you have the choice to operate with the keyboard or sending goals to move_base so that it can compute a trajectory and follow it automatically. See [Section 3 Autonomous navigation](http://wiki.ros.org/rtabmap_ros/Tutorials/MappingAndNavigationOnTurtlebot#Autonomous_Navigation) of the tutorial.
