### ISSUE TITLE
Should Nodelets not use nodelet_error not ros_error

### ISSUE THREAD

**Issue by rnunziata** [introlab/rtabmap_ros#51]
Should Nodelets not use nodelet_error not ros_error

**Comment by matlabbe** [comment]
I suppose! Well, I changed them in this commit 6b5ccf9. However, I am not sure where is the difference (comparing the outputs in [rqt_console](http://wiki.ros.org/rqt_console)) between `NODELET_INFO` (which calls `ROS_INFO_NAMED(getName(), ...)`) and `ROS_INFO`. It is maybe because I just tried with a standalone nodelet, not with a nodelet manager as in this [post](http://answers.ros.org/question/10799/what-are-the-differences-between-running-a-nodelet-standalone-and-running-the-same-nodelet-alone-in-a-manager/).

cheers
