### ISSUE TITLE
Build docker image including opencv non free modules.

### ISSUE THREAD

**Issue by Mikor-mkr** [introlab/rtabmap_ros#630]
Hello, 

I am interested in making a docker image which is building the rtabmap ros with libpointmatcher and opencv non free modules but I would love some advice because I am messing this up. Anyone has any idea?

**Comment by matlabbe** [comment]
This [one](https://github.com/introlab/rtabmap_ros/blob/master/docker/noetic/latest/Dockerfile) is built on this [one](https://github.com/introlab/rtabmap/blob/master/docker/focal/Dockerfile) and has libpointmatcher support. If you want OpenCV built from source with nonfree, use same version than the [one in focal](https://packages.ubuntu.com/focal/libopencv-dev) (which seems to be 4.2), build it and install it from source somewhere [here](https://github.com/introlab/rtabmap/blob/c5e4d67f8003b4a46aeac6e46c9db4000ae24c29/docker/focal/Dockerfile#L12) so that rtabmap builds upon it. Make sure /usr/local is in the PATH so that rtabmap finds it first before the system's one. By building the same OpenCV version than the system version, you don't have to rebuild `cv_bridge` package from source ith all pacakages depending on it.

Second option is to uninstall libopencv-dev, and rebuild all ros packages depending on opencv.
