### ISSUE TITLE
Ground detection off

### ISSUE THREAD

**Issue by kiprock** [introlab/rtabmap_ros#672]
Hello, I am testing rtab-map with isaac sim using a single rgb+depth camera. I am having issues where the ground plane is not horizontal, even though the camera is pointing forward. I'm having this issue if I use robot odom or visual odom. Any suggestions as to how to debug? The camera is very low to the ground.

![image](https://user-images.githubusercontent.com/17282763/139776799-8cb4f46c-e15d-4ec7-8d2b-26333ea8e970.png)

**Comment by matlabbe** [comment]
If the whole point cloud is tilted, in general it is because the static TF of the camera is not correctly set (not matching the reality). As this is a simulator, I would assume that TFs are perfect if they are taken from same model. It could be wrong camera calibration intrinsics or wrong depth values. Do you have a database to share?

**Comment by kiprock** [comment]
I would have thought the same. I checked the camera TF several times, and even played with the forward rotation.. Perhaps the intrinsics provided by Issac Sim are wrong?

http://kiphaynes.com/LIL/rtabmap11-2.db

**Comment by kiprock** [comment]
The camera intrinsics published by isaacsim seem to be causing the issue. When I generated a calibration file in the simulation, the ground issues becomes resolved. Closing.
