### ISSUE TITLE
Problem with package depthimage_to_laserscan

### ISSUE THREAD

**Issue by DistinctVision** [introlab/rtabmap_ros#706]
Hello. I'm trying to use the 'depthimage_to_laserscan' package (to convert RGBD frame shape to LaserScan). Also I am using move_base to control the robot and I need occupancy grid data from RTAB-Map for move_base. And I get this script:
  1. An RGBD frame is converted to LaserScan in the depthimage_to_laserscan package.
  2. RTAB-Map is waiting for LaserScan data, but the delay is too long. And it gets the first frame without LaserScan data. There is no LaserScan data in the first keyframe. The occupancy grid keeps empty.
  3. Occupancy grid keeps empty => move_base isn't working => robot isn't moving.
  4. The robot isn't moving => no new keyframes are created.
  I solved this problem by ignoring non-LaserScan frame data if needed.
  My fork:
https://github.com/BrainGardenAI/rtabmap_ros/tree/fix_laser_scan_bug

**Comment by matlabbe** [comment]
The real question is why "There is no LaserScan data in the first keyframe"? Taking too long is not a good reason, as rtabmap callback is called only if it receives a scan topic, in this case the received scan topic is empty. Why is it empty? Is it because depthimage_to_laserscan received an empty depth image, then republished an empty laser scan?

Other option is to force rtabmap to update the map with any new scans even if the robot is not moving, set `map_always_update` parameter to true.

Though not optimal, second option is to force rtabmap to update the map even if the robot is not moving, by setting `RGBD/LinearUpdate` parameter to 0.

For good graph optimization, it is preferred adding a new node at constant rate than skipping a node because there is no sensor data (in case the empty laser scan issue happens also while moving).

cheers,
Mathieu

**Comment by DistinctVision** [comment]
I don't think the laser scan input is empty. My fix only ignores the input if the laser scan in data is empty, but laser scan message is not.
```
        if (!scan2dMsg.ranges.empty() && data.laserScanRaw().isEmpty())
	{
		ROS_WARN("Received null laser scan!");
		return;
	}
```
But the solution with the 'map_always_update' flag is suitable. Thanks.

**Comment by matlabbe** [comment]
Indeed, the input scan may not be empty, containing only NaNs or Inf values, which are filtered in data by [laserScan2dFromPointCloud](https://github.com/introlab/rtabmap/blob/a648365e534002601c1f3b5f4622cdf5d850fe3a/corelib/include/rtabmap/core/util3d.h#L223-L232) function (with `filterNaNs=true` by default) here:
https://github.com/introlab/rtabmap_ros/blob/f22a69d1cec3e3643b7b94a2a91534cbe4a0a16f/src/MsgConversion.cpp#L2237-L2252

This event could happen when the robot is moving in a clear space, but we would still want to add the poses to graph as explained in my previous post even if the lidar (or fake lidar) is hitting nothing.

cheers,
Mathieu
