### ISSUE TITLE
Use the detect_more_loop_closures service with 3D lidar

### ISSUE THREAD

**Issue by cantolini** [introlab/rtabmap_ros#727]
Hi, 

I am using rtabmap on a simulated robot on ROS Galactic, trying to get the best out of it with a 3D lidar.
Looking at the post processing in the Edit menu of the rtabmap-databaseViewer tool, the map can be improved with "Detect more loop closures..", and numerous loop closures are detected.

Now I would like to make it "more automatic". I've seen there is a service that can be called as follows:
`ros2 service call /rtabmap/detect_more_loop_closures rtabmap_ros/srv/DetectMoreLoopClosures "{cluster_radius_max: 1.0, cluster_radius_min: 0.0, cluster_angle: 30.0, iterations: 1, intra_only: false, inter_only: false}"`
but with rtabmap running with a 3d lidar, I get the response: 
`rtabmap_ros.srv.DetectMoreLoopClosures_Response(detected=0)`

However, when I add a camera to the simulation, by calling the same service loop closures are this time detected.

Given that using only a 3D lidar, more loop closures are detected in rtabmap-databaseViewer but not calling the DetectMoreLoopClosures service, my question is what is the difference between the two?
And is there a way for this service to work with rtabmap running only on scan_cloud?

Thanks in advance!

**Comment by matlabbe** [comment]
This is the one from `rtabmap-databaseViewer`:
https://github.com/introlab/rtabmap/blob/860c14e0ecbc1ca79eff783a60d087d742c9dedb/guilib/src/DatabaseViewer.cpp#L4087

This is the one called from the service:
https://github.com/introlab/rtabmap/blob/860c14e0ecbc1ca79eff783a60d087d742c9dedb/corelib/src/Rtabmap.cpp#L5305

They were implemented in parallel but they should generate a similar result. However, if you don't have a camera, the one in database uses the graph as to compute the first guess for ICP. The problem is that the service one required parameter "RGBD/ProximityOdomGuess" set to true to work with lidar-only registration. I changed the parameter in this [commit](https://github.com/introlab/rtabmap/commit/83693ed1b9d836029fac5b17237cbc13f16cb1fb) to make it working by default with lidar-only registration.
