### ISSUE TITLE
rtabmap/goal_node frame_id issues

### ISSUE THREAD

**Issue by Nosille** [introlab/rtabmap_ros#731]
I have been testing the path planning features of rtabmap.  Everything works find if I simply enter a node_id.  However, I have found an issue that occurs if I assign a value to frame_id in the rtabmap/goal_node message as follows:

rostopic pub /rtabmap/goal_node rtabmap_ros/Goal "header:
  seq: 0
  stamp:
    secs: 0
    nsecs: 0
  frame_id: ''
node_id: 208
node_label: ''
frame_id: 'map'" 

I suspect a problem with CoreWapper.cpp around line 2304.  should frameId_ be mapFrameId_?

**Comment by matlabbe** [comment]
Hi,

Actually, the `frame_id` in the msg doesn't mean in which fixed frame we want to republish the goal. It means which frame on the robot that we want to align with the goal (for example, align the `camera_link` with the node instead of `base_link`). This was added in this commit: https://github.com/introlab/rtabmap_ros/commit/c09eabd2915dc8fa399a03d1b73d5433ae29498d

You should set nothing to directly use the base frame of the robot. However, I don't remember for which specific case this option has been added 3 years ago, as in most cases, base frame of the robot would be used.

Note that for `/rtabmap/goal` topic, the pose is transformed in map frame before planning (if not already in map frame).

cheers,
Mathieu
